default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: "1234"
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: poolwatch_development


test:
  <<: *default
  database: poolwatch_test

production:
  <<: *default
